### ISSUE TITLE
Combine rotate and resize into 1 custom control 

### ISSUE THREAD

**Issue by davidrossiter** [pixolith/fabricjs-customise-controls-extension#13]
First off this extension is an amazing addition to fabricjs, customizing the controls is such a big part of making the canvas fit in with your design. So glad I've found it!

Something I have not come across and think would be great is the possibility to combine the two controls rotate and scale into 1 control. This gives the user far easier/quicker control over rotating objects and sizing them how they want - it also reduces the buttons by 1 for those - like me - looking to have a simpler interface which is generally a better UI.

With just 1 click/drag you could size and angle the object how you want, this is especially good for using fabricjs on mobile devices when you're using your thumb or finger for adjusting.

Here is an example of 1 control controlling both: https://streamable.com/mmxi

**Comment by MDSLKTR** [comment]
Hey there, thank you for kind words :). Really appreciate it!.

The combination of resize and scale would probably require to overwrite a bigger part of the fabric.js core. The hard part for instance is to hook into the mousemove listener that will change the scaling or rotation depending on which corner action you use. I think it can be done though but would require a good amount of time. `_performTransformAction` is the function in the core you should looking for.

For touch devices it can actually be done a bit easier if you for instance use a libary like hammer.js
(http://hammerjs.github.io/getting-started/) to manage your touch events. You can easily bind it to the upper canvas of fabric.js like so:
`hammerManager = new Hammer.Manager( this.getCanvas().upperCanvasEl );`
in combination with a pinch and rotate you basicly have what you are looking for but only for touch gestures of course (http://hammerjs.github.io/recognize-with/).

You can then add and use them like this (where event would be the desired hammer.js event)

`hammerManager.add( [ pinch, rotate ] );`
`hammerManager.on( event, callback );`

Inside the callback you would need to find the active Object with `cObject = canvas.getActiveObject()`

After that really you can put anything inside a fabric animate function and set whatever value you like for instance:

`
( function animate() {
        currentObject.scaleX = e.scale;
        currentObject.scaleY = e.scale;
        setTimeout( function() {
             canvasManager.getCanvas().renderAll();
      }, 16 );
} )();
`

So i would probably consider getting this to work with mouseevents in the future but i cannot give you a real timeframe on it at the moment unless you want to give it a shot. For the touch handling you can already do as mentioned above. Let me know what you think.

Regards,
Simon

**Comment by davidrossiter** [comment]
Thanks for the reply, sorry for the delay commenting back! The explanation you've given is really great, especially the details on touch. I'm glad to hear it should be easier for touch devices combined with hammer.js as that is the platform I am looking for it to work on. 

After taking a look it may be a little out of my depth, if I do manage to get there I'll post an update :)

**Comment by MDSLKTR** [comment]
Closed since no update regarding this issue.
