### ISSUE TITLE
Multiple object have same properties?

### ISSUE THREAD

**Issue by blu94** [pixolith/fabricjs-customise-controls-extension#14]
how to make multiple different object have same properties at once?
this is my code, it is not efficiency
rect1.customiseCornerIcons({
    settings: {
        borderColor: 'transparent',
        cornerSize: 45,
        cornerShape: 'rect',
        cornerBackgroundColor: 'white',
        cornerPadding: 10
    },
    tl: {
        icon: 'computing-cloud.svg'
    }
});
rect2.customiseCornerIcons({
    settings: {
        borderColor: 'transparent',
        cornerSize: 45,
        cornerShape: 'rect',
        cornerBackgroundColor: 'white',
        cornerPadding: 10
    },
    tl: {
        icon: 'computing-cloud.svg'
    }
});
rect3.customiseCornerIcons({
    settings: {
        borderColor: 'transparent',
        cornerSize: 45,
        cornerShape: 'rect',
        cornerBackgroundColor: 'white',
        cornerPadding: 10
    },
    tl: {
        icon: 'computing-cloud.svg'
    }
});

**Comment by MDSLKTR** [comment]
Hey there, if all objects share the same setup you can simply use the prototype for setting everything up like this:

`
fabric.Object.prototype.customiseCornerIcons( {                   
    settings: {                     
       borderColor: 'transparent',
            cornerSize: 45,
            cornerShape: 'rect',
            cornerBackgroundColor: 'white',
            cornerPadding: 10
        },
        tl: {
            icon: 'computing-cloud.svg'
        }
    } );
`

Let me know if this helps,

Regards,
Simon
