### ISSUE TITLE
Canvas is not immediatly updated on remove() or layer functions in fabric 1.6.3

### ISSUE THREAD

**Issue by MDSLKTR** [pixolith/fabricjs-customise-controls-extension#16]
Possible Bug in fabric.js See: https://github.com/kangax/fabric.js/issues/3083

**Comment by iwilliams** [comment]
@MDSLKTR 

Just now I was having this same issue, I was able to fix it by overriding the remove action to the following:

``` JavaScript
action: function( e, target ) {
    if ( this.getActiveGroup() && this.getActiveGroup() !== 'undefined' ) {
        this.getActiveGroup().forEachObject( function( o ) {
            o.remove();
        } );
        this.discardActiveGroup();
    } else {
        let canvas = target.canvas;
        canvas.remove(target).renderAll();
        canvas.getActiveObject().remove()
    }
}
```

I'm not sure if this bug has to do with Fabric itself or this library so I don't know if it is appropriate to open a PR on this, also not sure if my solution is ideal.

**Comment by MDSLKTR** [comment]
@iwilliams 

Thank you for your response. I think something has changed in the api for sure as you cannot invoke remove() on the object itself anymore and getting an update. In the examples it is now always invoked on the canvas with the object as argument. I think i will make an update on this taking your code into account as it is probably the only working way at the moment.

**Comment by MDSLKTR** [comment]
You should stick to fabric 1.6.2 for now until this is resolved, it seems like the activeObject is not properly removed when the render happens, this might be because an event is fired on the icon again when the remove is invoked, restoring the object.

**Comment by iwilliams** [comment]
Running into some other strange bugs in 1.6.3, I've reverted back to 1.6.2 for the time being.

**Comment by MDSLKTR** [comment]
@iwilliams this is now fixed in release 0.1.6 here.

**Comment by websuvius** [comment]
Hello,
this bug is happening again in fabric 1.6.5 and 1.6.6.

**Comment by MDSLKTR** [comment]
Hello,
thank you very much for reporting it. I will update the extension to the newest fabric dist sometime during the next days and then take a look. I was really hoping it was resolved but the rendering process might have changed again..

**Comment by MDSLKTR** [comment]
@websuvius for me this working in the newest fabric.js dist (1.6.6). Check the example [Page](http://pixolith.github.io/fabricjs-customise-controls-extension/example/index.html) here again since i have updated it to fabric.js 1.6.6. If it is still not working for you, we can try to investigate further.
