### ISSUE TITLE
Inline SVG is not working

### ISSUE THREAD

**Issue by anbiniyar** [pixolith/fabricjs-customise-controls-extension#19]
Thank you for this library. It truly is easy to use. While using it I found the following bug

If try to use inline svg like below for `customiseCornerIcons` function, it throws a warning saying that the image is invalid. 

`data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gU3ZnIFZlY3RvciBJY29ucyA6IGh0dHA6Ly93d3cub25saW5ld2ViZm9udHMuY29tL2ljb24gLS0+DQo8IURPQ1RZUEUgc3ZnIFBVQkxJQyAiLS8vVzNDLy9EVEQgU1ZHIDEuMS8vRU4iICJodHRwOi8vd3d3LnczLm9yZy9HcmFwaGljcy9TVkcvMS4xL0RURC9zdmcxMS5kdGQiPg0KPHN2ZyB2ZXJzaW9uPSIxLjEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IiB2aWV3Qm94PSIwIDAgMTAwMCAxMDAwIiBlbmFibGUtYmFja2dyb3VuZD0ibmV3IDAgMCAxMDAwIDEwMDAiIHhtbDpzcGFjZT0icHJlc2VydmUiPg0KPG1ldGFkYXRhPiBTdmcgVmVjdG9yIEljb25zIDogaHR0cDovL3d3dy5vbmxpbmV3ZWJmb250cy5jb20vaWNvbiA8L21ldGFkYXRhPg0KPGc+PHBhdGggZD0iTTUwMCwxMEMyMjkuNCwxMCwxMCwyMjkuNCwxMCw1MDBjMCwyNzAuNiwyMTkuNCw0OTAsNDkwLDQ5MGMyNzAuNiwwLDQ5MC0yMTkuNCw0OTAtNDkwQzk5MCwyMjkuNCw3NzAuNiwxMCw1MDAsMTB6IE0zNDQuMiw3NjcuMUgyMzIuOVY2NTUuOGwzMjgtMzI4bDExMS4zLDExMS4zTDM0NC4yLDc2Ny4xeiBNNzU4LjIsMzUzLjFMNzAzLjMsNDA4TDU5MiwyOTYuN2w1NC45LTU0LjljMTEuOS0xMS45LDI5LjctMTEuOSw0MS41LDBsNjkuOCw2OS44Qzc3MC4xLDMyMy40LDc3MC4xLDM0MS4yLDc1OC4yLDM1My4xeiIvPjwvZz4NCjwvc3ZnPg==`

After digging through your code, I found out that removing `icon.crossOrigin = 'Anonymous'` in `loadIcon` fixes this issue. 

I am thinking of just retrying the `loadIcon` without cross origin for extra measure. I would like to hear your thought on this. Right now I am a little tied up so I decided to open an issue instead. I will see if I can submit a pull request later.

**Comment by MDSLKTR** [comment]
Hello,
thank you for reporting this. This was intially a fix to not being able to export canvases that contained icons from external urls. So i now know that this only needs to be set when it's an external url.

**Comment by MDSLKTR** [comment]
This is fixed in 0.1.5 now. I would recommend loading the svg from a .svg file though, because this causes loads of encoding errors when base64ing an svg. It won't work as a corner icon like this probably. You can easily save the contents to something.svg though when opening it in a browser.

**Comment by anbiniyar** [comment]
Like you suggested, I wanted to serve the .svg as a separate file. My current project right now forces me to use base64 as a temporary measure until I figure out a solution around it. 

I verified that that the corner icon actually works using base64, at least for my use case. Thanks again for taking the time to fix this bug.
