### ISSUE TITLE
Possibility to draw controls "outside the box"

### ISSUE THREAD

**Issue by Gogac** [pixolith/fabricjs-customise-controls-extension#22]
Hi,
would be great that we have option to place Controls outside the object box. I'm busy with some mobile app and controls are a bit bigger and sometimes are over text/image.

I'm new with Fabric Js and still exploring the code. Maybe it's easy but i can not see it. So far i manage to draw Controls outside the box simple by adding **this.cornerSize** to width and height.

```
(line 165)
var wh = this._calculateCurrentDimensions( true ),
   width = wh.x + this.cornerSize,
   height = wh.y + this.cornerSize,
   scaleOffset = this.cornerSize,
   left = -( width + scaleOffset ) / 2,
   top = -( height + scaleOffset ) / 2,
   methodName;
```

But that is only visual movement. Actual controls are still where they were. Can you help me with this?
![would-be-great](https://cloud.githubusercontent.com/assets/13254927/17464383/3a42e760-5cdd-11e6-9d85-490c1098c718.jpg)
What i did partially but when i place cursor above controls i noticed that is only visual effect.

![what-we-have](https://cloud.githubusercontent.com/assets/13254927/17464384/43b102fa-5cdd-11e6-8fac-cbb3297c843a.jpg)
What we have originally. I can set padding to controls but that is not what i want.

Thanks

**Comment by MDSLKTR** [comment]
Hello, thank you for reporting this. Unfortunatly, this is something i have looked into before and it is not easily possible to change this. As you already described, it will only shift the controls visually. What you might be able to do is though is to use an inner Padding on the text element like this:

yourTextObject.padding = 20;

That would get you some space between the inner area and the controls box. Hopefully this is helpful. Let me know :)

Regards,
Simon

**Comment by Gogac** [comment]
I got it :). So far works perfect exactly how i want. As soon as i catch some time i will add on/off possibility. I'm still testing that.
btw, i know for padding option, but that also move rect box away from object and that is not what i want.

**Comment by tborealis** [comment]
@Gogac could you report back on how you solved it?

**Comment by MDSLKTR** [comment]
Closed since no updates.

**Comment by marvinhuebner** [comment]
@Gogac could you give a report how you solved this?

**Comment by ohader** [comment]
I've implemented this functionality basically which can be enabled per `fabric.Object` instance with e.g. `myObject.cornerOutside = true;`.

Find the adjustments for this here (some rebasing might be required for current upstream):
https://github.com/ohader/fabricjs-customise-controls-extension/commit/689639f6b35a844d725bd875fe448114a50ad059

![bildschirmfoto 2017-05-17 um 11 39 33](https://cloud.githubusercontent.com/assets/402145/26149263/f4e2a664-3af9-11e7-8437-f77b871e2ca6.png)
