### ISSUE TITLE
more modification for specific corner

### ISSUE THREAD

**Issue by RJason13** [pixolith/fabricjs-customise-controls-extension#23]
i found your extension really useful for me, but there are some feature that you can add but you haven't. 

i want to change cornerBG and corner shape, but only for specific corner like for delete button (red) and for scaleX (mr: diff shape) and scaleY (mb:  diff shape), and also after you enable that feature you can add more shape like a horizontal sausage for scaleY and vertical sausage for scaleX. i've read your code and i found it quite easy to add these features. this is an example of result of my modification to your code:

![image](https://cloud.githubusercontent.com/assets/15855266/18899093/b8fd7de4-8560-11e6-899f-322c6cd466d5.png)

i think it'll be useful for the others too

**Comment by MDSLKTR** [comment]
Hey there and sorry for the late response (holidays). First of thank you for using this extension and tinkering with it :). If you want you can always shoot me a pull request for your changes. As you said this could be a nice and useful feature i would be more than willing to merge.

**Comment by RJason13** [comment]
well, i modified a copy of your file and maybe i modified it not so cleanly, so, i think i will just attach my file here so you can get the idea and probably you want to create the cleaner version

![image](https://cloud.githubusercontent.com/assets/15855266/19142578/95e9682c-8bc8-11e6-8b40-68c3974ae04d.png)

this is what i do in my app core, i hope it will help :)

modified file: [customiseControlsModified.zip](https://github.com/pixolith/fabricjs-customise-controls-extension/files/513015/customiseControlsModified.zip)

**Comment by MDSLKTR** [comment]
Great thank you! I'll take a look soon and see what i can make of it.

**Comment by MDSLKTR** [comment]
This is now partially included in https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.2.6.

Basicly you can set these settings for each corner now, but the custom corner shapes you added caused problems on edge corners which is why they are not included for now. Great Stuff!

**Comment by RJason13** [comment]
cool, thanks i'll use it soon 👍
