### ISSUE TITLE
Resize.svg not shown in Firefox browser

### ISSUE THREAD

**Issue by Robertdegraaf** [pixolith/fabricjs-customise-controls-extension#24]
In the firefox browser the resize.svg icon is not showing. On your demo link you can see the error http://pixolith.github.io/fabricjs-customise-controls-extension/example/index.html. If I change the resize.svg in remove.svg the icon will show in for example tl position. De diagonal-resize.svg will also not show.

**Comment by MDSLKTR** [comment]
Hello,
thank you for reporting this. It appears that width and height attributes need to be set on the svgs for it to  be displayed in firefox. This is very weird as svgs should scale independant from fixed dimensions. I will update the example to properly display all icons. The Bug however i would put into svg quirks category for now.

**Comment by MDSLKTR** [comment]
This now fixed in https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.1.8 and on the example Page.

**Comment by Robertdegraaf** [comment]
Can you tell me how you fixed this problem. I want the resize.svg to be mirrored but when I save this svg the new svg will also not be visible.

**Comment by MDSLKTR** [comment]
Hello again,
yes you need to additionally set width="" and height="" attributes on the svgs to get them displayed in Firefox. Check this [Commit](https://github.com/pixolith/fabricjs-customise-controls-extension/commit/4d4e14bf44069404db84140ff85aa48987b51073).
