### ISSUE TITLE
The problem of FontFamily changed

### ISSUE THREAD

**Issue by Lucassssss** [pixolith/fabricjs-customise-controls-extension#33]
Hi there, The great extension saving life.
I`m using the extension to font, The border width have some problem when the font family changed.
![s](https://cloud.githubusercontent.com/assets/5128154/22731154/a2516c9a-ee24-11e6-9988-f429ed2c52a9.png)

**Comment by MDSLKTR** [comment]
Hey there, thank you for reporting this. Could you by any chance whip up a small testcase on codepen for instance? Otherwise some code posted here would be useful, so i can determine which parts are possibly breaking.

**Comment by Lucassssss** [comment]
Finally, I found that is not the extension`s  problem. 
Here is the demo,

https://jsfiddle.net/LucasWang/toekxzen/

When i editing The text, The border`s width will be bug. I think the problem is cause by The FontFamily self, and the issues should not  be here. Sorry for your time.

**Comment by MDSLKTR** [comment]
Hey there, no problem at all :), I'll close this then and good luck with your project.
