### ISSUE TITLE
fabric.js depenency

### ISSUE THREAD

**Issue by robinflyhigh** [pixolith/fabricjs-customise-controls-extension#38]
In bower.json the dependencies should be set to fabric.js instead of fabric because in my bower folder two fabric projects are downloaded.

"dependencies": {
    "fabric.js": "~1.7.9"
  }

**Comment by MDSLKTR** [comment]
Hey there, i see. On npm it's only called fabric. I shall correct that 👍

**Comment by MDSLKTR** [comment]
This is now fixed in https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.2.5.
