### ISSUE TITLE
Offset icons outside bounding box

### ISSUE THREAD

**Issue by thejmill** [pixolith/fabricjs-customise-controls-extension#4]
Is there a way to move the icons further out so they don't overlap the bounding box and hide content?

**Comment by MDSLKTR** [comment]
`obj.set( {
           padding: 20
        } );`

You can set this to increase the bounding box by an inner padding between itself and the image. Hope this is what you're looking for.

**Comment by thejmill** [comment]
This is a good solution however it does not work in our scenario.  When we add more padding to the element box it causes it to go outside the bounding box and show it as not being withing the designated area.  Ideally we would like the selection box to have 0 padding and the corner controls to be on the outside of the selection box as show in the attached image.

![boundingbox](https://cloud.githubusercontent.com/assets/1775476/13079611/0e2308c2-d493-11e5-9d2e-ec9f16352608.png)

**Comment by MDSLKTR** [comment]
Ah i see, i can't promise you anything yet since i need to see whether this doesn't go too deep into the core, but i will check it out. It certainly could be a good feature to have certain control position offsets.
Thank you for your input so far. I am also always open to pull requests in case you have an idea.

Simon

**Comment by MDSLKTR** [comment]
It looks to me that this is very heavy hack into the fabric.js core. It is possible to move the position of the corner icon itself, but the event handlers are fixed to a certain position in each corner. Moreover It is generally very hard to get the exact bounding box of a text element for instance which makes it almost impossible to get the real 'edges' of the text where the icon should sit. I would say that this is probably not an easy feature if even possible.
