### ISSUE TITLE
Issue with Fabric cache

### ISSUE THREAD

**Issue by robinflyhigh** [pixolith/fabricjs-customise-controls-extension#40]
Hello,

Please check the jsfiddle @ https://jsfiddle.net/robinflyhigh/vqjq3z8v/2/

If you remove the shape first then js error is thrown but if you remove the text first then it will work fine.

This issue happens only when we add objectCaching: true for text.

When we use it without 'fabricjs-customise-controls-extension' it works fine.

Any clue what is wrong?

**Comment by MDSLKTR** [comment]
Hey there, thanks for reporting this. I will have a look asap.

**Comment by MDSLKTR** [comment]
Hey again, this is an issue with objectCache trying to slice your custom action function as a string. I converted the action to a void string after execution so the type check doesn't fail. Please test the latest release and close this if everything is fine :).

https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.2.9

**Comment by robinflyhigh** [comment]
Works

**Comment by robinflyhigh** [comment]
Thanks a lot @MDSLKTR

**Comment by MDSLKTR** [comment]
No problem man, happy to help!
