### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by SmboBeast** [pixolith/fabricjs-customise-controls-extension#43]
This library seems great and it's what I've been looking for.  However, I can't seem to get things working.

I'm literally just adding FabricJS (any of the newer ones), along with the CustomizeControls JS file, and everything loads fine.  Drawing on the canvas is fine also.  However, when selecting and moving any object, I get these errors attached.

Going through the examples, nothing is really different on my side.  Please help.

![screen shot 2017-05-25 at 7 43 41 am 1](https://cloud.githubusercontent.com/assets/287007/26455132/22202050-411e-11e7-90f6-b4c5bf8104f3.png)

**Comment by MDSLKTR** [comment]
Hey man, thank you for reporting this. This looks like a weird error as i also include a pretty new version of fabric in my example. Mind putting up a small testcase or sharing some code, so i can investigate whats going on?

Regards,
Simon

**Comment by SmboBeast** [comment]
Hey Simon,

Thanks for the prompt reply.  Let me figure out the best way to have you see this test case.  My code is intertwined with React (which can somehow be getting in the way).  I will surely update you as soon as I can get something in front of your eyes.

Thanks!
Sam

**Comment by MDSLKTR** [comment]
Hey Sam,

Sure thing! I have only used this in an Angular context before but when i hear react, it could be due to react not autobinding functions in event handlers in es6 classes, where you oddly have to do this.functionname = this.functionname.bind(this) in your constructor. Just a wild guess though :D

Regards,
Simon

**Comment by SmboBeast** [comment]
Simon,

Finally got some time to jump back on this again.  I'm not sure how I can have you play with this firsthand, but maybe this would be enough for you to understand what's going on.  

I don't think it's a React binding thing, because things seem to be binding just fine.  I'm including a screen shot here.  

I'm also just using the basic code you have here: [https://github.com/pixolith/fabricjs-customise-controls-extension#customising-the-controls](url) once my React component is loaded and can access clientside Javascript.  Nothing fancy there really.

![screen shot 2017-06-02 at 11 51 31 pm](https://cloud.githubusercontent.com/assets/287007/26751461/dc33e9f0-47ee-11e7-93a2-95e2e0a9aadc.png)

Thanks!

**Comment by SmboBeast** [comment]
Might be the explicit + 'Rect' piece????

**Comment by MDSLKTR** [comment]
Hey thank you for following up. I think you caught a breaking change in fabric. When not using customIcons from my extension the `methodName` previously was set to `fillRect/strokeRect` directly. In the newest fabric version it is set to fill/stroke and 'Rect' is appended later. So now it was trying to invoke `fillRectRect()` which will throw an error. I am fixing it now, will let you know.

**Comment by MDSLKTR** [comment]
Hopefully fixed in https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.3.1. Please let me know 👍

**Comment by SmboBeast** [comment]
Thank you.  Errors are fixed.  Now I just have to figure out why the UI doesn't render something like the following below.  However, the actions work just fine - the top left button actually removes the layer when clicked and the cursor is also a pointer upon hover too.

fabric.Canvas.prototype.customiseControls({
        settings: {
          borderColor: 'black',
          cornerSize: 25,
          cornerShape: 'circle',
          cornerBackgroundColor: 'black',
          cornerPadding: 10,
        },
        tl: {
          action: 'remove',
          cursor: 'pointer',
        },
        tr: false,
        bl: false,
        br: {
          action: 'scale',
        },
        mb: false,
        mr: false,
        mt: false,
      });

**Comment by MDSLKTR** [comment]
You are trying to pass the settings in on the canvas prototype for the controls (`fabric.Canvas.prototype.customiseControls()`) which unfortunatly only lets you define the actions and cursors.
Pass your settings in` fabric.Object.prototype.customiseCornerIcons()` which overwrites the correct prototype for fabric objects.

```
fabric.Object.prototype.customiseCornerIcons({
        settings: {
            borderColor: '#0094dd',
            cornerSize: 25,
            cornerShape: 'rect',
            cornerBackgroundColor: 'black',
        },
    }, function() {
        canvas.renderAll();
    });
```

**Comment by SmboBeast** [comment]
You are great!  Thank you for all your help and work putting this library together.  Saves us all time and effort instead of having to write out own.  We appreciate your work!

**Comment by MDSLKTR** [comment]
Thank you very much for the kind words! Really appreciate it! Glad i could help.
