### ISSUE TITLE
Some options don't render as they should

### ISSUE THREAD

**Issue by SmboBeast** [pixolith/fabricjs-customise-controls-extension#44]
Hi,

When not using custom icons, the code below doesn't actually render accordingly.  No matter what, corner icons are squared and the default blue outline is rendered.  Is the code below supposed to make all objects have black circles as their corners?

fabric.Object.prototype.customiseCornerIcons({
        settings: {
          borderColor: 'black',
          cornerSize: 25,
          cornerShape: 'circle',
          cornerBackgroundColor: 'black',
          cornerPadding: 10,
        },
      }, function() {
          canvas.renderAll();
      });

**Comment by MDSLKTR** [comment]
Hey again,

I will have a look, could be the case that since no icon is selected the settings will just jump to default which is incorrect as you stated.

Regards,
Simon

**Comment by MDSLKTR** [comment]
Shoud be fixed in:
https://github.com/pixolith/fabricjs-customise-controls-extension/releases/tag/0.3.2

**Comment by SmboBeast** [comment]
It works perfectly.  I sent over some beer as a thank you.  ;)
