### ISSUE TITLE
Control icons out of canvas

### ISSUE THREAD

**Issue by magebay99** [pixolith/fabricjs-customise-controls-extension#45]
However, a very big issues when I added an  image larger size than canvas, all the custom control icons are also go out of canvas size.

Is there a solution to keep it stay in canvas for this happen?

Thank you so much for great extension!

**Comment by MDSLKTR** [comment]
Hey there,
thank you! I think your best bet is to control the image dimensions when rendering it on the canvas. There is a scaleX and scaleY property on the image object. You could of course try to limit the position of the image to the current canvas size, which would help with the controls staying visible. Other than that, i don't think there is an interface handling this particular problem. The controls simply stick on the edges, so you would need to control that in a way that fits your application.

Regards,
Simon

**Comment by MDSLKTR** [comment]
I'll close this question for now. Please re-open if you need further support.
