### ISSUE TITLE
callback use？

### ISSUE THREAD

**Issue by Charles9292** [pixolith/fabricjs-customise-controls-extension#46]
problem：When I click on the upper right corner the element is not deleted
[My code](https://jsfiddle.net/Charles_/r9ytud3o/)
_**no run**_

**Comment by MDSLKTR** [comment]
Hey there, thanks for reporting this. Could you try the following lines instead in your ajax cb:

```
target.off();
target.remove();
```

And if that doesn't do it (there used to be a workaround needed for force removing and re-rendering) append this (but only if really needed :P):

```
setTimeout(function() {
canvas.deactivateAll();
}, 0);
```

Regards,
Simon

**Comment by Charles9292** [comment]
This method won't work, click Two clicks to delete.
This way `action: 'remove'` can be run.
But I want to do something after I delete it.
So I use the callback way.
The same question [link](https://stackoverflow.com/questions/45031060/canvas-click-the-picture-to-generate-the-fork)

**Comment by MDSLKTR** [comment]
Hey again, i get your intentions. Even with the combination of
```
target.off();
target.remove();
setTimeout(function() {
    canvas.deactivateAll();
}, 0);
```
it wont delete in one click?

The way above is basically how `action: 'remove'` works internally. So this can run in your callback as well easily.

Regards,
Simon

**Comment by Charles9292** [comment]
```
action: function (e, target) {
  setTimeout(function() {
    ajax({
      delete: 1
    }, function(data) {
      target.off()
      target.remove()
      toastr.success('deleted！')
    })
  }, 0)
},
```
That's what my code says.
Still need to click two clicks to delete.

**Comment by MDSLKTR** [comment]
Hey again,
try it with this:

```
action: function (e, target) {
  ajax({
      delete: 1
    }, function(data) {
      target.off()
      target.remove()
      setTimeout(function() {
          canvas.deactivateAll()
          toastr.success('deleted！')
      }, 0)
    })
},
```

Regards,
Simon

**Comment by Charles9292** [comment]
May be set up `fabric.Object.prototype.renderOnAddRemove = false`
I try not to set this property to normal delete
Most of the time
But there's a new problem
after adding code`if (!confirm('delete？')) return`
not functioning properly
[new question](https://jsfiddle.net/Charles_/r9ytud3o/1/)

**Comment by MDSLKTR** [comment]
Hey again, i am not exactly sure what you are trying to do but 

```
if (!confirm('delete？')) return
```
does not work. You can't return out of a confirm.
This might work

```
if (confirm('delete？') {
ajax({
          cmd: 'delete'
        }, function(data) {
        	setTimeout( _ => {
            target.off()
            target.remove()
        }, 0)
}
```
Regards,
Simon
