### ISSUE TITLE
Add cornerSize option to individual corner's settings?

### ISSUE THREAD

**Issue by faniva** [pixolith/fabricjs-customise-controls-extension#47]
Right now, you can customize the corners separately by passing a settings object like this : 

``` 
fabric.Object.prototype.customiseCornerIcons({
            settings: {
                borderColor: '#3867fd',
                cornerSize: 25,
                cornerShape: 'circle',
                cornerBackgroundColor: '#1444fd',
                cornerPadding: 12
            },
            tl: {
                icon: 'images/icons/remove.svg',
                settings : {
                   cornerBackgroundColor: 'red',
                   cornerPadding: 20
                }
            },
...
 ```

The options to customize are limited to "cornerShape", "cornerBackgroundColor" and "cornerPadding".
Could you please add "cornerSize" too?

**Comment by MDSLKTR** [comment]
Hey,

thank you for the request. Shouldn't be too much of a problem. Will do when i get the time.

Regards,
Simon

**Comment by faniva** [comment]
Hi, 
Thanks for getting back to me. I wrote a solution just now before I saw your reply and made a push to the repository. Hope it helps! 
Another request, maybe font-awesome support? That'd be cool

**Comment by christikaes** [comment]
I would like this feature too! Created a PR ^ based on @josefano suggestion (:

**Comment by MDSLKTR** [comment]
Hi @christinakayastha,

thank you very much for the PRs! Immediate PRs are always welcome. I will take a look either today or tomorrow and release a new version including the current fabric.js build.

Regards,
Simon

**Comment by MDSLKTR** [comment]
This is now in 0.3.4
