### ISSUE TITLE
Minified version isn't the same as formatted

### ISSUE THREAD

**Issue by DanieleSassoli** [pixolith/fabricjs-customise-controls-extension#5]
Hi,
It look's like the minified version in the dist folder isn't the same as the formatted version. I noticed this because _rotateByDegrees() is different across the 2 files, not sure about the others...

**Comment by MDSLKTR** [comment]
Hey,
thank you very much for reporting this. It could have been a hickup in the grunt build process while pushing the latest version. I will recompile everything along with the pull requests you made for both branches and push a new release tag.

-Simon

**Comment by DanieleSassoli** [comment]
perfect, thanks!

**Comment by MDSLKTR** [comment]
Should be working now in 0.0.9.
