### ISSUE TITLE
Demo page has broken link to fabric.js, unviewable

### ISSUE THREAD

**Issue by justin-hackin** [pixolith/fabricjs-customise-controls-extension#51]
It's a real shame because this extension is awesome !  I'm glad I went the extra mile to download repo and npm install deps because the from text description I did not have good idea about the full range of possibilities and your demo did a great job of showing that.

**Comment by MDSLKTR** [comment]
Hey there, thanks for opening an issue about this since i broke the page with todays update :D. Should all be working again now! And thanks for the kind words!
