### ISSUE TITLE
control cursor broken with fabric@2.0.0

### ISSUE THREAD

**Issue by justin-hackin** [pixolith/fabricjs-customise-controls-extension#54]
Works fine with fabric@1.7.9 but latest fabric@2.0.0-beta-6 does not show proper cursors
see https://jsfiddle.net/vt04qL81/
swap commented fabric.js version (used in example) to observe expected behavior

**Comment by MDSLKTR** [comment]
Hey,

Version 2 of fabric.js is currently not supported as i don't have the time to keep up with beta changes. I will probably try to make it work when 2.0 is out of beta.
Nonetheless, PRs are always welcome.

Regards,
Simon

**Comment by kotay** [comment]
Looks like Fabric 2.0 is out of beta now, any idea when support for 2.0 will come?

**Comment by MDSLKTR** [comment]
@kotay hey there,
I'll see what i can do but due to time aren't actively following the fabric development. It might be too much work for now. PRs are always welcome though.

Regards,
Simon
