### ISSUE TITLE
Getting security error when use customisecontrols in IE 11

### ISSUE THREAD

**Issue by nitin-bc** [pixolith/fabricjs-customise-controls-extension#56]
Hi,

When i use customisecontrols property then i am getting security error issue in IE 11 at the time of exporting the data from canvas using canvas.toDataURL(). Can someone please let me know the solution for the same? Its little bit urgent.

Thank you in advance

**Comment by MDSLKTR** [comment]
Hey there, thank you for reporting this. What kind of images did you use as controls? Also i assume this is not happening when no corner controls have images?

Regards,
Simon

**Comment by nitin-bc** [comment]
Hi, thanks for your response. I am getting this issue while using custom controls. I think this is happening due to cross origin issue but the image files i am using on same server. Also while i am trying the image from google path like this @ http://pixolith.github.io/fabricjs-customise-controls-extension/example/index.html. It seems working. I am not sure what is strange.

**Comment by MDSLKTR** [comment]
Hey again, you could try to set the crossOrigin attribute on the image if IE 11 supports it. Something like ```img.crossOrigin = 'anonymous';```. Otherwise maybe this thread helps? https://stackoverflow.com/questions/16956295/ie10-and-cross-origin-resource-sharing-cors-issues-with-image-canvas
