### ISSUE TITLE
Need to draw custom instead of icon

### ISSUE THREAD

**Issue by engrsandeep** [pixolith/fabricjs-customise-controls-extension#57]
Hi @MDSLKTR 

I have to add some size notification of object in bottom and left of object. Is it possible with your plugin. Same attached below.

![image](https://user-images.githubusercontent.com/10007250/30198346-d962e2ba-948a-11e7-8615-6acc8ee86906.png)

**Comment by MDSLKTR** [comment]
Hey there, thank you for your question! This however is not really the focus of this plugin but it should be possible with plain fabric.js since you can create disabled text or shape elements and position them next to the movable object. You only need to sync positions of the elements.

Regards,
Simon

**Comment by engrsandeep** [comment]
Hi @MDSLKTR,

Thanks, i have achieved this by grouping of objects.

I encountered one issue cursor not changing as per functionality. I have used below code to customiseControls but it not showing pointer cursor. Can you help?

fabric.Canvas.prototype.customiseControls({                    
            tr: {
                action: function( e, target ) {
                    self.deleteObject(target)                    
                },
                cursor: 'pointer',
            },            
            br: {
                action: 'rotate',
                cursor: 'pointer'
            }
        }, function() {
            self.canvas.renderAll();
        });

**Comment by MDSLKTR** [comment]
Hey there,
is none of them showing a pointer cursor? Or just one specific corner? Other than that, which fabric.js version are you using?

Regards,
Simon

**Comment by engrsandeep** [comment]
@MDSLKTR i have used latest fabric version 2.0.0-beta6. Which one you recommend?

**Comment by MDSLKTR** [comment]
Hey again,
fabric 2 is currently not officially supported as it is still beta and i dont have the time to keep up with changes. The latest fabric 1 schould work as expected.

Regards,
Simon
