### ISSUE TITLE
Problem with Reactjs

### ISSUE THREAD

**Issue by ajeetvarma** [pixolith/fabricjs-customise-controls-extension#59]
I am using this plugin with React js . After dragging an image to board the following error in console is coming : 

> customiseControls.js:205 Uncaught TypeError: this._setLineDash is not a function
>     at klass.drawControls (customiseControls.js:205)
>     at klass._renderControls (fabric.js:11624)
>     at klass._draw (fabric.js:6432)
>     at klass._renderObjects (fabric.js:6566)
>     at klass.renderAll (fabric.js:6537)
>     at klass.setActiveObject (fabric.js:9000)
>     at Board.handleDrop (board.js:157)

Then i edited the code in customiseControls.js on line 205 by commenting that line like this :  
       ` // this._setLineDash([ctx, this.cornerDashArray, null]);`
Then after i again dragged then it works partially . It appears the control icons but when i clicked on image the following error in console coming : 

> Uncaught TypeError: Cannot read property 'altKey' of undefined
>     at klass._shouldCenterTransform (fabric.js:8371)
>     at klass._resetCurrentTransform (fabric.js:8228)
>     at klass._setupCurrentTransform (customiseControls.js:571)
>     at klass.__onMouseDown (fabric.js:9622)
>     at klass._onMouseDown (fabric.js:9338)
>    _shouldCenterTransform @ fabric.js:8371
>    _resetCurrentTransform @ fabric.js:8228
>    _setupCurrentTransform @ customiseControls.js:571
>    __onMouseDown @ fabric.js:9622
>    _onMouseDown @ fabric.js:9338
> 
Although icon functionalities works but after clicking on board image , image simply drags with mouse without selecting the image . 

I do't know why this problem is coming in React Js.
Reactjs version is ^15.4.2.

Please help me to resolve this issue .

Thanks a lot in advance ..

**Comment by MDSLKTR** [comment]
Hey there and thanks for your report!
I doubt it's a problem with react. Which fabric.js version are you running and how are you including the plugin in your code?

Regards,
Simon

**Comment by ajeetvarma** [comment]
Thanks for your response .
I am using Fabric 1.6.0-rc.1 version .
I have used fabric-webpack package .

Regards,
Ajeet

**Comment by MDSLKTR** [comment]
Hey again,
please try with a recent stable version of fabric.js. 1.7.17 and upwards should be good. Version 2 is not supported. Your version might be too old and is not stable.

Regards,
Simon

**Comment by ajeetvarma** [comment]
Thanks a lot ! It works like a charm !! :+1:

**Comment by MDSLKTR** [comment]
Glad i could help :)
