### ISSUE TITLE
cornerStrokeColor can not be set 

### ISSUE THREAD

**Issue by Luca-A-Mueller** [pixolith/fabricjs-customise-controls-extension#60]
Hello, 

first thank you for providing us with this great extension, it is very helpful and intuitive. 

Our versions are: 
```
    "fabric": "1.7.14",
    "fabric-customise-controls": "0.3.5",
```

We are using it to substitute fabrics control corners with some svg icons to push the control
nodes outside of the borders. 

However it seems that the original corners are still present after loading a svg.
_Is this expected behaviour?_ 

I started formatting the corner itself: 

with fabric-customise-controls:

      tl: {
        icon: '../../assets/static/cornerIcons/tl.svg',
        settings: {
          cornerBackgroundColor: 'rgba(0,0,0,0)',
          cornerStrokeColor: 'rgba(0,0,0,0)',
        },
      },  ...  });

and with fabric itself: 

```
    this.borderScaleFactor = 2;
    this.rotatingPointOffset = 25;
    this.borderColor = 'rgb(0,93,166)';
    this.cornerShape = 'rect';
    this.cornerPadding = 20;
    this.cornerSize = 25;
    this.setControlsVisibility({
      tl: true,
      tr: true,
      br: true,
      bl: true,
      ml: false,
      mt: false,
      mr: false,
      mb: false,
      mtr: true,
    });
    this.transparentCorners = false;
```

I'm negating the *transparentCorners* so that I should be able to set the _cornerStrokeColor_.

However the cornerStroke remains white regardless of the color I choose.

![image](https://user-images.githubusercontent.com/32836427/31606467-6f3b6af4-b269-11e7-9d44-9c68910e80f0.png)

**Comment by MDSLKTR** [comment]
Hey there,

thanks for your report.

`However it seems that the original corners are still present after loading a svg.
Is this expected behaviour?`

Yes this is due to limitations of the fabric.js corner implemenation. You cannot easily move the click areas. It has been done though, but very hacky.

Concerning the corner stroke:  The last value of rgba is alpha which means opacity and 0 means your cornerStrokeColor is basicly not there. Try rgba(0,0,0,1).

Regards,
Simon

**Comment by Luca-A-Mueller** [comment]
Hi Simon,

thank you for the quick response. 
I should have clarified, that my intention was to set both the cornerBackgroundColor and the cornerStrokeColor to transparent. 

This works for cornerBackgroundColor: 
`          cornerBackgroundColor: 'rgba(0,0,0,0)',
`
but not for cornerStrokeColor. 

As I said the cornerStroke remains white regardless of the color I choose.

Cheers, 
Luca

**Comment by MDSLKTR** [comment]
Hey again,

sorry for the late response. You should see the questions that are usually asked, so i assumed to start with the basics, no offense :P. Please try the new release 0.3.6. You should now be able to overwrite the settings per corner even when cornerStrokeColor is set on the object itself. This won't solve the clicking area problem though, sadly.

Regards,
Simon
