### ISSUE TITLE
Upgrade to fabric 2.0

### ISSUE THREAD

**Issue by MDSLKTR** [pixolith/fabricjs-customise-controls-extension#61]
Since fabric 2 has it's release candidates a 2.0 branch might be required soon.

**Comment by reesemartin** [comment]
If you change your extension's override of "_setCornerCursor" to "getCornerCursor" which is what fabricjs has renamed that to, the custom corner cursor will work with versions after fabricjs's commit https://github.com/kangax/fabric.js/commit/03e504303c4e216b520b1d6486606010ea610d8b

**Comment by MDSLKTR** [comment]
@reesemartin Hey, thank you for the input. It would be amazing if that was it. Was expecting a much larger chore to get it working. Will try it asap.

Thanks.

**Comment by MDSLKTR** [comment]
@reesemartin feel free to check out the next branch. It looks like it's working now. Needed more changes but nonetheless might not be complete yet.

**Comment by MDSLKTR** [comment]
https://github.com/pixolith/fabricjs-customise-controls-extension/tree/next

**Comment by reesemartin** [comment]
Yes I did have to make those active object changes in my fabricjs code when upgrading. I am using this plugin primarily for the custom icons, custom hover cursor, and my own functions on click so I did not catch the need for those changes in your code. Great job catching that those needed changed. Love the plugin. Thanks!
