### ISSUE TITLE
Can't assign different cursor for controls

### ISSUE THREAD

**Issue by dczii** [pixolith/fabricjs-customise-controls-extension#62]
Hi, I am having a problem in applying different cursor for each controls that I assigned. The cursor can't seem to change even though I changed the cursor in my code. I have followed properly the documentation you have on your page. here's a link to simulate the problem. 
[JSFiddle Link](https://jsfiddle.net/dczii/aehLfaps/241/)

**Comment by MDSLKTR** [comment]
Hey there. Thanks for your report. When using version 2.x of fabric.js you need to also use the 2.0.0-beta from the @next branch of this repository. When changing the customiseControls.js to https://unpkg.com/fabric-customise-controls@2.0.0-beta/dist/customiseControls.js in your fiddle, the cursor change works. Hope this helps.

**Comment by dczii** [comment]
wow great!! works perfectly. You can close this issue now. thank you so much.

**Comment by MDSLKTR** [comment]
Great, no problem :)

**Comment by dczii** [comment]
hi @MDSLKTR additional question here. I am now migrating my fiddle to reactjs component. how can I choose the next branch when importing it in my component?

**Comment by dczii** [comment]
@MDSLKTR nevermind my question, I think I figured it out on my own. changing the version in package.json seems the answer.
