### ISSUE TITLE
Cursor style is not appear on object corner.

### ISSUE THREAD

**Issue by appledev44** [pixolith/fabricjs-customise-controls-extension#65]
I used customise controls extension. But I see the one thing about cursor. Cursor style is not applying to corner. I tried to apply crossHair and pointer. Can you tell me what I missed in code.
Please check the fiddle.
https://jsfiddle.net/jogvx768/9/

**Comment by MDSLKTR** [comment]
Hey there, when using fabric.js 2 and above you need to install the @next branch of this repository or fetch the release (2.0.0-beta) in your package.json in order for it to work. Take a look here: https://github.com/pixolith/fabricjs-customise-controls-extension/issues/62. I tried it in your fiddle and the cursors change as expected.
Regards,
Simon
