### ISSUE TITLE
Can't custom the controls for specify object?

### ISSUE THREAD

**Issue by GreatAuk** [pixolith/fabricjs-customise-controls-extension#70]
```
const text = new fabric.Text(...)
text.customiseControls(...)
```
Get a error:  Uncaught TypeError: text.customiseControls is not a function

**Comment by MDSLKTR** [comment]
Hey there,

`customiseControls` extends the Canvas prototype not the Object prototype and therefore can only be applied to your canvas instance (see: https://github.com/pixolith/fabricjs-customise-controls-extension#customising-the-controls). You can use `customiseCornerIcons` on your text object though.

Regards,
Simon

**Comment by GreatAuk** [comment]
@

> Hey there,
> 
> `customiseControls` extends the Canvas prototype not the Object prototype and therefore can only be applied to your canvas instance (see: https://github.com/pixolith/fabricjs-customise-controls-extension#customising-the-controls). You can use `customiseCornerIcons` on your text object though.
> 
> Regards,
> Simon

Thank you for your reply👍
