### ISSUE TITLE
Property 'customiseControls' does not exist on type Canvas angular 7.2.15 

### ISSUE THREAD

**Issue by jawad-aziz-farhad** [pixolith/fabricjs-customise-controls-extension#71]
I'm trying to implement custom controls in my angular 7 project. Versions are as fellows:
"@angular/core": "~7.2.15",
"fabric": "^2.7.0",
"fabric-customise-controls": "^2.0.2-beta",

after importing fabric-customise-controls in my component using this 
import 'fabric-customise-controls';

When I tried to implement customization code, 

`fabric.Canvas.prototype.customiseControls({
    tl: {
        action: 'rotate',
        cursor: 'cow.png'
    },
    tr: {
        action: 'scale'
    },
    bl: {
        action: 'remove',
        cursor: 'pointer'
    },
    br: {
        action: 'moveUp',
        cursor: 'pointer'
    },
    mb: {
        action: 'moveDown',
        cursor: 'pointer'
    },
    mt: {
        action: {
            'rotateByDegrees': 45
        }
    },
    mr: {
        action: function( e, target ) {
            target.set( {
                left: 200
            } );
            canvas.renderAll();
        }
     },
     // only is hasRotatingPoint is not set to false
     mtr: {
        action: 'rotate',
        cursor: 'cow.png'
     },
}, function() {
    canvas.renderAll();
} );`

it give me error as mentioned in the title.

**Comment by MDSLKTR** [comment]
Hey thanks for reporting this. Could you maybe provide a minimal codepen / codesandbox for me to figure out whether its framework related or a problem in the code itself?

**Comment by jawad-aziz-farhad** [comment]
Please use this repo to reproduce this issue:
**https://github.com/jawad-aziz-farhad/Custom-Controllers**
Uncomment this function **customControls()** and you will see this issue.
Thanks

**Comment by jawad-aziz-farhad** [comment]
Hi @MDSLKTR , 
I'm really sorry. just realised that I didn't push the relevant code to this repo. please have a look now.

**Comment by jawad-aziz-farhad** [comment]
I also created a plunker [here](https://next.plnkr.co/edit/aN3AabBiKUmVtGOz?preview). You can also check that.

**Comment by MDSLKTR** [comment]
Hey, no problem! For me the plunker is working though. If I click on the bottom left corner the action is correctly triggered as remove instead of the default. Also the prototype is applied as you can see in my screenshot.
![image](https://user-images.githubusercontent.com/9129687/58501198-1cc74b80-8184-11e9-835d-e624805c373f.png)

Maybe a different browser than Chrome?

**Comment by jawad-aziz-farhad** [comment]
I can also see this but angular's compiler can't get this. its giving the same error.

**Comment by jawad-aziz-farhad** [comment]
ok. I got it working by doing the following code. As I need it for the IText object which is at 0 index of canvas. 

`const icons = [
    'assets/_images/circle.svg',
    'assets/_images/rotate.svg',
    'assets/_images/expand.svg'
  ];
this.canvas.item(0)['customiseCornerIcons']({
    settings: {
        borderColor: 'black',
        cornerSize: 25,
        cornerShape: 'rect',
        cornerBackgroundColor: 'black',
        cornerPadding: 10
    },
    tl: {
        icon: icons[0],
        settings: {
            cornerShape: 'rect',
            cornerBackgroundColor: 'red',
            cornerPadding: 10,
            // since 0.3.4
            cornerSize: 15
        },
    },
    tr: {
        icon: icons[1]
    },
    br: {
        icon: icons[2]
    }
}, () => {
    this.canvas.renderAll();
} );`
