### ISSUE TITLE
Corner size is not properly detected when individual cornerSize is larger than global cornerSize

### ISSUE THREAD

**Issue by Granga** [pixolith/fabricjs-customise-controls-extension#74]
My goal is to have all corners to show as small squares, and rotation handle to be icon and larger than the rest of the corners.
I was able to do that, but when I hover the rotation handle, cursor does not change until it's right at the center of the handle. This is because when detecting edges of the handle fabric uses different `cornerSize` than the number specified for the rotation handle.
Here's a fiddle reproducing the problem:

https://jsfiddle.net/Granga/tfgaurx6/14/

I came up with a solution, and a pull request will follow.

**Comment by MDSLKTR** [comment]
Merged and released as 2.0.6-beta, thanks!
