### ISSUE TITLE
Change control fill color while scaling?

### ISSUE THREAD

**Issue by mbejda** [pixolith/fabricjs-customise-controls-extension#76]
Does this library offer the ability to change control fill color while scaling? I'm trying to achieve something similar to this. 

![captured](https://user-images.githubusercontent.com/5429780/61369769-21110a80-a891-11e9-832e-deaf59bb8396.gif)

**Comment by MDSLKTR** [comment]
Hey there. Well this should work by listening to the corresponding fabric.js event and reinitializing `customiseControls` with the proper config "on scale". The same for "on scaleend" and redrawing the the canvas when doing so.

**Comment by mbejda** [comment]
Thank you
