### ISSUE TITLE
Error _resetCurrentTransform is not a function not campatible Fabric 5

### ISSUE THREAD

**Issue by ivent** [pixolith/fabricjs-customise-controls-extension#82]
this script does an amazing job, but unfortunately it's not working anymore on fabric version ^5.2.1 I get an error 

```
this._resetCurrentTransform is not a function
     at klass._setupCurrentTransform (customiseControls.js:685:1)
```
could someone adapt the code to the latest version of fabric or do you have another workaround to customize the command icons in svg?

**Comment by MDSLKTR** [comment]
Thank you for the kind words. I was hoping fabric would deliver this functionality in the core by now since i havent been using it for a long time. There seems to be something for custom controls now (http://fabricjs.com/docs/fabric.Object.html#controls). Maybe thats a starter.

**Comment by ivent** [comment]
Hi, thank you very much for your help, I found that Fabric created this function in the latest versions and finally managed to create custom controls, thanks for your collaboration http://fabricjs.com/custom-control-render
